### ISSUE TITLE
Don't check validation of an input if it is hidden with a `conditionalPanel()`

### ISSUE THREAD

**Issue by isaactpetersen** [rstudio/shinyvalidate#48]
I'd like to have an option not to check validation if an input is hidden with a `conditionalPanel()`. I'd like to require answers to all of my items. However, using branching logic, I hide some items based on participants' responses with a `conditionalPanel()`, and I would not like their validation to be checked on the items that are hidden. Consider the following example:

```
1. What is your favorite sport? (radio button input)

a. baseball
b. basketball
c. football
d. soccer
e. other (please specify)

2. You selected "other"--please specify: (textbox input)
```

Let's say I show Item 2 conditionally only when "other" (option `e`) is selected for Item 1. I want both items to be required, but only if the item is shown to participants. I don't want validation to be checked for Item 2 unless it is shown.

The reason why this would be helpful is that I'd like to allow participants to proceed to the next survey only after they have completed all (shown) items. However, `iv$is_valid()` evaluates as `FALSE` because some of the "required" items are hidden based on their responses and they do not have an opportunity to complete them.

**Comment by ismirsehregal** [comment]
You can deactivate the validation using `iv$disable()` (with `iv` beeing your InputValidator) whenever the condition to hide your input is met. Use `iv$enable()` to activate it back again.

[Here](https://community.rstudio.com/t/best-practices-for-validating-user-input-with-an-actionbutton-and-eventreactive/110153/4?u=ismirsehregal) is an example.

**Comment by isaactpetersen** [comment]
Thanks for your note. If I understand, using `iv$disable()` would disable the entire InputValidator. However, I have multiple items stored in the InputValidator, and I want to disable *only* those items that are hidden by a conditional panel (not all of the items are hidden). I could create a separate InputValidator for each item, but that would be a hassle and would not fit be very efficient codewise. Would it be possible to selectively ignore some items when checking validation if an item is hidden from the user? If not, I'd like this to be a feature request.

**Comment by jcheng5** [comment]
@isaactpetersen That's a good suggestion. Today, Shiny doesn't track what inputs are visible (though it does track what _outputs_ are visible) so there's not an easy way for us to add this in an automatic way. However, you could work around it less painfully than creating a nested `InputValidator`, by using `skip_validation()`:

```r
iv <- InputValidator$new()

iv$add_rule("favorite_sport", sv_required())

iv$add_rule("other", ~ if (!identical(input$favorite_sport, "other (please specify)")) skip_validation())
iv$add_rule("other", sv_required())
```

The Getting Started guide doesn't talk about it, but validation rules can actually return not two but _three_ possibilities: `NULL` if this rule passes, a string if there's an error, or `skip_validation()` if all further rules for this particular input should be skipped.

Note that order matters, i.e. be sure to have your `skip_validation()` rule appear earlier than any rules you want skipped.
