### ISSUE TITLE
add_rule is not working for selectInput when multiple=TRUE

### ISSUE THREAD

**Issue by toddcreasy** [rstudio/shinyvalidate#78]
Hi,

When I change a selectInput with multiple=TRUE, the "Required" message does not appear below the dropdown and cannot be validated. When I change to multiple=FALSE, it does work. Anything I'm missing? I realize the below example isn't very complete but I'm just wondering if there is a limitation to shinyvalidate for multi-select.

```
 selectInput(ns("indication"), 
                        label="Cancer Indication", 
                        choices=c("", sort(cancer.indications)), 
                        selected="", 
                        multiple=TRUE,
                        width='100%'))
```

This is the rule I'm using with a condition:

```
ssiv$add_rule("indication", sv_required())
ssiv$condition(~ input$indication == "")
```

**Comment by zsigmas** [comment]
Hi Todd,

If I am not wrong the problem is that you are checking if the selected value is `""`. But in fact when a `selectInput` is empty and multiple is `TRUE` the returned value is `NULL`. You can check https://shiny.posit.co/r/reference/shiny/latest/selectinput

Find below a working app using a multiple selector with `shinyvalidate`.

```r
shiny::shinyApp(
    ui = shiny::fluidPage(
        shiny::selectizeInput("l", "letters", letters, multiple = TRUE),
        shiny::verbatimTextOutput("o")
    ),
    server = function(input, output, session){
        iv <- shinyvalidate::InputValidator$new()
        iv$add_rule("l", function(x){if(is.null(x)) "Select at least one" else NULL})
        iv$enable()

        output[["o"]] <- shiny::renderPrint(input[["l"]])
    }
)
```

**Comment by toddcreasy** [comment]
Hi Luis,

Great catch! Thanks for the help!

-todd
